@endpoint =  https://19ufnv5k3b.execute-api.ap-southeast-2.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/properties?propertyId=a379fcd8-48eb-450f-ad76-350616f2a583
###

GET {{endpoint}}/properties?status=Completed
###

GET {{endpoint}}/properties
###

POST {{endpoint}}/properties/
Content-Type: application/json

{
    "address": "4 East Coast Road, Queenstown, Auckland",
    "status": "Pending"
}
###