@endpoint =  https://19ufnv5k3b.execute-api.ap-southeast-2.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/property?propertyId=a379fcd8-48eb-450f-ad76-350616f2a583
###

POST {{endpoint}}/property/
Content-Type: application/json

{
    "address": "4 East Coast Road, Queenstown, Auckland",
    "status": "Pending"
}
###